### ISSUE TITLE
v0.6.0: flag provided but not defined: -s3-endpoint-url

### ISSUE THREAD

**Issue by denisgorbunov** [InseeFrLab/s3-operator#86]
I'm encountering an issue when deploying the inseefrlab/s3-operator Helm chart (version 0.6.0 ) to manage MinIO resources. The operator's container crashes with the error `flag provided but not defined: -s3-endpoint-url`, even though I followed the documentation. 

The s3-operator Deployment fails to start because it includes the `--s3-endpoint-url` flag in its command arguments. However, this flag is not recognized by the operator's executable (as seen in the logs).

The generated Deployment YAML (via helm template) includes the problematic flag:
```yaml
containers:  
  - name: manager  
    command:  
      - /manager  
    args:  
      - --health-probe-bind-address=:8081  
      - --metrics-bind-address=127.0.0.1:8080  
      - --leader-elect  
      - --s3-endpoint-url=cdn.tk8s.local:443  # Problematic flag  
      - --bucket-deletion=false  
      # ... other arguments  
```

**Could the maintainers**:
1. Confirm if --s3-endpoint-url is a valid flag in v0.6.0?
2. Clarify how to configure the MinIO endpoint for the operator?
3. Address this discrepancy in the Helm chart or documentation?

Thank you for your help!
